### ISSUE TITLE
rebranding

### ISSUE THREAD

**Issue by brenzi** [integritee-network/integritee-node#19]
replace all SubstraTEE by integritee. Modify  Copyright notice to include both SCS and integritee

**Comment by echevrier** [comment]
Same comments as for the sgx-runtime rebranding [#11](https://github.com/integritee-network/sgx-runtime/issues/11)

**Comment by echevrier** [comment]
Rename worker: integritee-worker or integritee-service in README?

**Comment by brenzi** [comment]
yes ,let's go for integritee-service

**Comment by brenzi** [comment]
we could introduce the two modes 
* OCW offchain worker
* SCV sidechain validateer

to clarify what a "service" could be
