### ISSUE TITLE
Fix Existential Deposit Config.

### ISSUE THREAD

**Issue by clangenb** [integritee-network/integritee-node#28]
While implementing https://github.com/integritee-network/worker/pull/376/commits/0a81f57b6895c5bde4572ca7d0ff952faff327c9, we discovered that we have a far too low ED (=500) set in the runtime.

We have properly configured runtime here: https://github.com/integritee-network/parachain/blob/5448e4e329100d3a9d1d7a44a30b8cb5e07a8dea/polkadot-parachains/integritee-runtime/src/lib.rs#L213

We can copy the setting from there, including the definition of the TEER.

**Comment by clangenb** [comment]
@brenzi do you a problem if we rename the token to `TEER` here too?

**Comment by brenzi** [comment]
don't know what you mean with "here"

**Comment by clangenb** [comment]
If it is a problem if we use TEER in the parachain and in the standalone node.

**Comment by brenzi** [comment]
no, that's fine. and might even be what will actually happen if we don't get a slot soon: launch standalone and join a relay-chain later. So, the token has to be TEER indeed
