### ISSUE TITLE
 add treasury

### ISSUE THREAD

**Issue by brenzi** [integritee-network/integritee-node#33]
we'll need a treasury on chain in order to allocate initial funding and collect fees

Please add the treasury pallet to the runtime and prepare genesis config so it will be allocated with 5% of total supply (so treasury should have 500'000 TEER initially)

configure the FeePayment such that it will collect fees in the treasury (which are currently burned entirely)

for now, the treasury should be under the control of `sudo`. governance pallets will follow later (or add them if they are a strict dependency of treasury)

**Comment by echevrier** [comment]
Where is the total supply define? Or shall I hardcode 500'000 TEER?

**Comment by echevrier** [comment]
When are fees paid?

**Comment by echevrier** [comment]
What about the weights?

**Comment by brenzi** [comment]
> Where is the total supply define? Or shall I hardcode 500'000 TEER?

in genesis definition.
https://github.com/integritee-network/integritee-node/blob/f7805838c03d5944ea18d4e5b2faec6cb59d5725/node/src/chain_spec.rs#L141

No "hardcoding". The genesis spec should say how much the initial balance of the treasury is. The accountid of the treasury is created here:
https://github.com/paritytech/substrate/blob/ce1746ddf6588c8f9ecfb77411c3cac7a2c09db3/frame/treasury/src/lib.rs#L246

**Comment by brenzi** [comment]
> When are fees paid?

This question is not clear. Whenever an extrinsic is included in a block, fees are paid

**Comment by brenzi** [comment]
> What about the weights?

please ask a question I can answer.

**Comment by echevrier** [comment]
> > Where is the total supply define? Or shall I hardcode 500'000 TEER?
> 
> in genesis definition.
> https://github.com/integritee-network/integritee-node/blob/f7805838c03d5944ea18d4e5b2faec6cb59d5725/node/src/chain_spec.rs#L141

What is the total supply ?  Nbr of endowed_account * 1 << 60 ? -> 4 * 1.1529 MTEER ? -> ~4612 TEER. In this case, the treasury will receive something like 230 TEER, which is very different from 500'000 TEER

**Comment by echevrier** [comment]
> > When are fees paid?
> 
> This question is not clear. Whenever an extrinsic is included in a block, fees are paid

I would like to know a concrete case to write a test.

**Comment by echevrier** [comment]
> > What about the weights?
> 
> please ask a question I can answer.

How shall we configure the weightInfo for the treasury pallet?

**Comment by brenzi** [comment]
weightInfo is automatically derived by benchmarking. That will be a separate task.

Test case:
2. send balances::transfer(...) extrinsic (1 TEER from //Alice to //Bob
2. Alices balance must be lower by 1 TEER + tx fee
3. Treasury balance must by raised by tx fee
4. once we have the burning function, the treasury will get less than the tx fee, because a fraction will "disappear" in the process

**Comment by echevrier** [comment]
Test case: 
there will be only an integration test in the woker client.
As tx fees are paid for block building, the test will pass when the treasury balance raised by more then the fee of the transfer.

**Comment by echevrier** [comment]
> Test case:
> there will be only an integration test in the woker client.
> As tx fees are paid for block building, the test will pass when the treasury balance raised by more then the fee of the transfer.
No need for a CI. The pallet has been fully tested. Here we only change the configuration. The manual test we did is therefore sufficient
