### ISSUE TITLE
introduce mainnet and testnet chainspec creation

### ISSUE THREAD

**Issue by brenzi** [integritee-network/integritee-node#34]
Our standalone mainnet should have a similar setup as we recently did for parachain.

We should offer the following `--chain` options
* `integritee-mainnet`: this will return the pre-generated spec from a chain-spec json file file stored in the repo (like shell-kusama for the parachain)
* `integritee-mainnet-fresh` this should generate a chain spec with the same sudo key as for the parachain that we can then commit to be used for the above
* `cranny`: public TESTNET, this will return the pre-generated spec from a chain-spec json file file stored in the repo. 
* `cranny-fresh`: dito

# integritee-mainnet
native token: TEER
ss58format: 13

* [x] define Babe authorities
   * 2PPzpwiTGvcgc4stV326en2mWqY1qFzhQ95SCqYZ4Q5dqwhJ
   * 2Px7JZCbMTBhBdWHT7cbC2SGqsVF2cFygdvdaYmuNgV53Bgh
   * 2PGjX1Nyq2SC7uuWTHWiEMQuJBMRupaefgaG5t6t588nFMZU
   * 2Jhqi21p3UdGu1SBJzeUyQM9FudC5iC7e4KryAuJ4NZMhYPe 
   * 2JwCMVvx8DgzpRD7sF1PKpzCDbmGiB2oa67ka2SuUe2TSJgB
* [x] define inital sudo account
   * 2JPGqddf4yEU7waYt7RMp9xwYabm16h8neYEk24tKQs4bAwN
# cranny
native token: `CRA`
ss58format: 42

* [x] define sudo account: 5CVcJfKKo7uqMGvAE9fzqw66tEfngwJat5FruAsa6hbSkejD
   * allocate 10M CRA to sudo at genesis
* [x] define Babe authorities:
   * 5DDBqKzDw4GnEVmqRXvo8iiWzFxT76E3KUDTk79NnM9F6B8V
   * 5GhK3Hm39J7yL6ZYoeUxynhfTkPxCd3EqnAPfgHcDo37wqmz
   * 5DHwmxfN57NvGpLYFFfxrshnGxccE12VbUGsFCzGSYZQKMfD

**Comment by clangenb** [comment]
Quick summary, of the tasks that I see:

1. Add in the [command.rs](https://github.com/integritee-network/integritee-node/blob/0d92564672ae1a370955a6a621c2d2fa34070117/node/src/command.rs#L52) the new specs: `integritee-mainnet-fresh` and `cranny-fresh`.
2. `integritee-fresh` and `cranny-fresh` should invoke some rust specs similar to the [chain_spec.rs](https://github.com/integritee-network/parachain/blob/b26bdd88009848b4511f69c81f2b7dfcaab3cd42/polkadot-parachains/src/chain_spec.rs#L135) in the parachain repo. They will only differ in this issue's params and pass them to a plain `fn chain_spec(chain_name, chain_id, chain_type, sudo_key, babe_authorities, token_params)` 
3. `chain_spec` will be the slightly adjusted [local_testnet_config](https://github.com/integritee-network/integritee-node/blob/0d92564672ae1a370955a6a621c2d2fa34070117/node/src/chain_spec.rs#L41) that takes the above parameters.
4. Then we create the two json-specs with the new `-fresh` rust chainspecs. Via `./integritee-node build-spec <chain-spec>-fresh > <chain-spec>.json`
5. Add the two json chain-specs commands in the command.rs, these to commands simply load the <chain-spec>.json from above similar to what we have in the [parachain](https://github.com/integritee-network/parachain/blob/b26bdd88009848b4511f69c81f2b7dfcaab3cd42/polkadot-parachains/src/chain_spec.rs#L273).
