### ISSUE TITLE
add dispatchable filtering for PoA mainnet launch

### ISSUE THREAD

**Issue by brenzi** [integritee-network/integritee-node#35]
When we launch a standalone mainnet, we don't want users to be able to send extrinsics immediately. Especially token actions need to be suppressed before the official token generation event

as done for parachain:
https://github.com/integritee-network/parachain/blob/75650f539c07de174ef6d4e0cd2c60347907fc30/polkadot-parachains/shell-runtime/src/lib.rs#L153-L161

But please disable all `Vesting` calls, not only `vested_transfer`

**Comment by echevrier** [comment]
Add vesting pallet to node
Block all vesting, multisig and balances commands only for standalone mainnet
Add compiler flag mainnet

**Comment by echevrier** [comment]
If we suppress all balances call, as is done in the parachain, we can't start the worker:
```
*** Starting integritee-worker
Worker Config: Config { node_ip: "ws://127.0.0.1", node_port: "9970", worker_ip: "127.0.0.1", worker_rpc_port: "2070", worker_mu_ra_port: "3443", ext_api_url: Some("ws://127.0.0.1:2070") }
IntegriTEE Worker v0.8.0
*** Starting enclave in development mode
MRENCLAVE=JD2S6LSgysK1HtQhCt84M5ta14UFx2Vat76YSqwDCcov
MU-RA server listening on ws://127.0.0.1:3443
[+] RPC direction invocation server listening on wss://127.0.0.1:2070
[+] bootstrap funding Enclave form Alice's funds
[!] skipping remote attestation. Registering enclave without attestation report.
[>] Register the enclave (send the extrinsic)
[2021-09-28T15:22:24Z ERROR ws::handler] WS Error <Custom(Extrinsic("extrinsic error code 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low)"))>
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexString(InvalidStringLength)', service/src/main.rs:336:71
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by echevrier** [comment]
What about the treasury calls?

**Comment by brenzi** [comment]
filter treasury calls too

**Comment by echevrier** [comment]
And what about the balances call? And this error?
> If we suppress all balances call, as is done in the parachain, we can't start the worker:
> 
> ```
> *** Starting integritee-worker
> Worker Config: Config { node_ip: "ws://127.0.0.1", node_port: "9970", worker_ip: "127.0.0.1", worker_rpc_port: "2070", worker_mu_ra_port: "3443", ext_api_url: Some("ws://127.0.0.1:2070") }
> IntegriTEE Worker v0.8.0
> *** Starting enclave in development mode
> MRENCLAVE=JD2S6LSgysK1HtQhCt84M5ta14UFx2Vat76YSqwDCcov
> MU-RA server listening on ws://127.0.0.1:3443
> [+] RPC direction invocation server listening on wss://127.0.0.1:2070
> [+] bootstrap funding Enclave form Alice's funds
> [!] skipping remote attestation. Registering enclave without attestation report.
> [>] Register the enclave (send the extrinsic)
> [2021-09-28T15:22:24Z ERROR ws::handler] WS Error <Custom(Extrinsic("extrinsic error code 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low)"))>
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexString(InvalidStringLength)', service/src/main.rs:336:71
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
