### ISSUE TITLE
include democracy pallet

### ISSUE THREAD

**Issue by brenzi** [integritee-network/integritee-node#73]
democracy is a secondary `RootOrigin` which can be triggered by coin voting. It is the most simple form of onchain governance and shall be our starting point.

needs to be tested and documented: how to perform a code update using democracy

**Comment by clangenb** [comment]
@brenzi, @haerdib what do we do after https://github.com/integritee-network/parachain/issues/108?

* Do we align the integritee-node runtime? Do we want to maintain it at all. I guess yes; the dev-experience is much better in the solo-node.

I'd personally vote to also include the council and democracy stuff in the integrtee-node, but still keep sudo around.

**Comment by brenzi** [comment]
We need to maintain the node, yes. But sudo stays for sure as it is for development only. We can add democracy, but I don't think we actually need that

**Comment by haerdib** [comment]
I can't think of the use case, either.

**Comment by clangenb** [comment]
Ok, then I close this issue. Thanks for the feedback.
